package mk.fikt.gamevault.data.auth

import android.content.Context
import android.content.Intent
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException

/**
 * Encapsulates Google Sign-In setup. Requires `default_web_client_id` string resource
 * generated by the google-services plugin from google-services.json. If that resource
 * is missing, [client] returns null and the UI must show a not-configured message.
 */
class GoogleSignInHelper(private val appContext: Context) {

    val client: GoogleSignInClient? by lazy {
        val webClientId = webClientIdOrNull() ?: return@lazy null
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(webClientId)
            .requestEmail()
            .build()
        GoogleSignIn.getClient(appContext, gso)
    }

    val isConfigured: Boolean get() = client != null

    fun signInIntent(): Intent? = client?.signInIntent

    fun signOut() {
        client?.signOut()
    }

    /**
     * Extract the Google ID token from the sign-in result intent.
     * Returns null if cancelled, errored, or sign-in helper is unconfigured.
     */
    fun parseIdToken(data: Intent?): String? = try {
        val task = GoogleSignIn.getSignedInAccountFromIntent(data)
        task.getResult(ApiException::class.java)?.idToken
    } catch (e: ApiException) {
        null
    }

    private fun webClientIdOrNull(): String? {
        val id = appContext.resources.getIdentifier(
            "default_web_client_id", "string", appContext.packageName
        )
        return if (id != 0) appContext.getString(id) else null
    }
}
